name: 🐛 Bug Report
description: Report a bug to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the information below to help us resolve this issue.

  - type: checkboxes
    attributes:
      label: Pre-flight Checklist
      description: Please ensure you've completed these steps before submitting a bug report
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I have tried reproducing this issue with the latest version
          required: true
        - label: I have read the [Contributing Guidelines](../../CONTRIBUTING.md)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Reproduction Code
      description: Please provide a minimal code example that reproduces the issue
      render: typescript
      placeholder: |
        // Minimal code example
        import { ConciergusProvider } from '@conciergus/chat';
        
        // Your reproduction code here

  - type: dropdown
    id: package-version
    attributes:
      label: Package Version
      description: What version of @conciergus/chat are you using?
      options:
        - 0.2.0 (latest)
        - 0.1.0
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: react-version
    attributes:
      label: React Version
      description: What version of React are you using?
      options:
        - 19.x
        - 18.x
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      options:
        - 20.x (LTS)
        - 18.x (LTS)
        - 22.x (Current)
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Windows
        - Linux (Ubuntu)
        - Linux (Other)
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser (if applicable)
      description: If this is a browser-related issue, which browser are you using?
      options:
        - Not applicable
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other (please specify in additional context)

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please copy and paste any relevant error logs or console output
      render: shell
      placeholder: Paste error logs here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, environment details, etc.)
      placeholder: Any additional information that might help us resolve this issue...

  - type: checkboxes
    attributes:
      label: Contributing
      description: Are you interested in contributing a fix for this issue?
      options:
        - label: I would like to work on a fix for this issue
          required: false 